/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // Manual top level so the external "Tutorials" link can sit between
  // Get Started and Relay (an autogenerated sidebar can't place a link
  // mid-list). Get Started's children stay autogenerated from its folder.
  tutorialSidebar: [
    {
      // Children listed explicitly: a manual category doesn't apply the
      // "index = category link" convention to autogenerated items (index.mdx
      // would duplicate as a child), and this gives direct order control. Add
      // new Get Started pages here.
      type: 'category',
      label: 'Get Started',
      link: {type: 'doc', id: 'get-started/index'},
      collapsed: false,
      items: [
        'get-started/creating-a-post',
        'get-started/viewing-feeds',
        'get-started/viewing-threads',
        'get-started/like-repost',
        'get-started/profiles',
        'get-started/following',
        'get-started/muting-and-blocking',
        'get-started/user-lists',
        'get-started/custom-feeds',
        'get-started/thread-gates',
        'get-started/video',
        'get-started/posts',
        'get-started/post-richtext',
        'get-started/timestamps',
      ],
    },
    {type: 'link', label: 'Tutorials', href: 'https://atproto.com/guides/tutorials'},
    'relay',
    'jetstream',
    // A few related docs are nested under a parent doc to keep the top level
    // to ~9-10 items. The category links to the parent doc itself.
    { type: 'category', label: 'API Hosts and Auth', link: { type: 'doc', id: 'api-directory' }, items: ['rate-limits', 'oauth-client']},
    {type: 'category', label: 'Resolving Identities', link: {type: 'doc', id: 'resolving-identities'}, items: ['entryway']},
    'oembed',
    'intent-links',
    {type: 'category', label: 'Bluesky Dev Guidelines', link: {type: 'doc', id: 'developer-guidelines'}, items: ['mailing-list']},
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
