import React from 'react'
import Link from '@docusaurus/Link'
import { useLocation } from '@docusaurus/router'

// Top-level docs sections, mirroring the autogenerated sidebar (kept in sync by
// hand — these are generated-index category routes, see each _category_.json).
const DOCS_LINKS = [
  { label: 'Get Started', to: '/docs/get-started' },
  { label: 'Tutorials', to: '/docs/category/tutorials' },
  { label: 'Starter Templates', to: '/docs/category/starter-templates' },
  { label: 'Advanced Guides', to: '/docs/category/advanced-guides' },
  { label: 'Support', to: '/docs/category/support' },
]

// Surfaces the docs sections inside the mobile hamburger on NON-docs routes
// (the homepage, blog, etc.), where Docusaurus wouldn't otherwise render a
// sidebar — so the menu isn't nearly empty there. On docs routes it returns
// null because the real sidebar already populates the drawer. Desktop: null
// (the masthead top bar carries navigation instead).
export default function DocsMenu({ mobile }) {
  const { pathname } = useLocation()
  if (!mobile) return null
  if (pathname.startsWith('/docs')) return null
  return (
    <>
      <li className="menu__list-item bpsDocsMenuHeading" aria-hidden="true">
        Documentation
      </li>
      {DOCS_LINKS.map((l) => (
        <li className="menu__list-item" key={l.to}>
          <Link className="menu__link" to={l.to}>
            {l.label}
          </Link>
        </li>
      ))}
    </>
  )
}
