import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/at-protocol-xrpc-api",
    },
    {
      type: "category",
      label: "app.bsky.actor",
      items: [
        {
          type: "doc",
          id: "api/app-bsky-actor-get-preferences",
          label: "app.bsky.actor.getPreferences",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-actor-get-profile",
          label: "app.bsky.actor.getProfile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-actor-get-profiles",
          label: "app.bsky.actor.getProfiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-actor-get-suggestions",
          label: "app.bsky.actor.getSuggestions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-actor-put-preferences",
          label: "app.bsky.actor.putPreferences",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-actor-search-actors",
          label: "app.bsky.actor.searchActors",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-actor-search-actors-typeahead",
          label: "app.bsky.actor.searchActorsTypeahead",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "app.bsky.ageassurance",
      items: [
        {
          type: "doc",
          id: "api/app-bsky-ageassurance-begin",
          label: "app.bsky.ageassurance.begin",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-ageassurance-get-config",
          label: "app.bsky.ageassurance.getConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-ageassurance-get-state",
          label: "app.bsky.ageassurance.getState",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "app.bsky.bookmark",
      items: [
        {
          type: "doc",
          id: "api/app-bsky-bookmark-create-bookmark",
          label: "app.bsky.bookmark.createBookmark",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-bookmark-delete-bookmark",
          label: "app.bsky.bookmark.deleteBookmark",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-bookmark-get-bookmarks",
          label: "app.bsky.bookmark.getBookmarks",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "app.bsky.feed",
      items: [
        {
          type: "doc",
          id: "api/app-bsky-feed-describe-feed-generator",
          label: "app.bsky.feed.describeFeedGenerator",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-actor-feeds",
          label: "app.bsky.feed.getActorFeeds",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-actor-likes",
          label: "app.bsky.feed.getActorLikes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-author-feed",
          label: "app.bsky.feed.getAuthorFeed",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-feed",
          label: "app.bsky.feed.getFeed",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-feed-generator",
          label: "app.bsky.feed.getFeedGenerator",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-feed-generators",
          label: "app.bsky.feed.getFeedGenerators",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-feed-skeleton",
          label: "app.bsky.feed.getFeedSkeleton",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-likes",
          label: "app.bsky.feed.getLikes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-list-feed",
          label: "app.bsky.feed.getListFeed",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-post-thread",
          label: "app.bsky.feed.getPostThread",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-posts",
          label: "app.bsky.feed.getPosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-quotes",
          label: "app.bsky.feed.getQuotes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-reposted-by",
          label: "app.bsky.feed.getRepostedBy",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-suggested-feeds",
          label: "app.bsky.feed.getSuggestedFeeds",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-get-timeline",
          label: "app.bsky.feed.getTimeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-search-posts",
          label: "app.bsky.feed.searchPosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-feed-send-interactions",
          label: "app.bsky.feed.sendInteractions",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "app.bsky.graph",
      items: [
        {
          type: "doc",
          id: "api/app-bsky-graph-get-actor-starter-packs",
          label: "app.bsky.graph.getActorStarterPacks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-blocks",
          label: "app.bsky.graph.getBlocks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-followers",
          label: "app.bsky.graph.getFollowers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-follows",
          label: "app.bsky.graph.getFollows",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-known-followers",
          label: "app.bsky.graph.getKnownFollowers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-list",
          label: "app.bsky.graph.getList",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-list-blocks",
          label: "app.bsky.graph.getListBlocks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-list-mutes",
          label: "app.bsky.graph.getListMutes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-lists",
          label: "app.bsky.graph.getLists",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-lists-with-membership",
          label: "app.bsky.graph.getListsWithMembership",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-mutes",
          label: "app.bsky.graph.getMutes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-relationships",
          label: "app.bsky.graph.getRelationships",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-starter-pack",
          label: "app.bsky.graph.getStarterPack",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-starter-packs",
          label: "app.bsky.graph.getStarterPacks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-starter-packs-with-membership",
          label: "app.bsky.graph.getStarterPacksWithMembership",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-get-suggested-follows-by-actor",
          label: "app.bsky.graph.getSuggestedFollowsByActor",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-mute-actor",
          label: "app.bsky.graph.muteActor",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-mute-actor-list",
          label: "app.bsky.graph.muteActorList",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-mute-thread",
          label: "app.bsky.graph.muteThread",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-search-starter-packs",
          label: "app.bsky.graph.searchStarterPacks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-unmute-actor",
          label: "app.bsky.graph.unmuteActor",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-unmute-actor-list",
          label: "app.bsky.graph.unmuteActorList",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-graph-unmute-thread",
          label: "app.bsky.graph.unmuteThread",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "app.bsky.labeler",
      items: [
        {
          type: "doc",
          id: "api/app-bsky-labeler-get-services",
          label: "app.bsky.labeler.getServices",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "app.bsky.notification",
      items: [
        {
          type: "doc",
          id: "api/app-bsky-notification-get-preferences",
          label: "app.bsky.notification.getPreferences",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-notification-get-unread-count",
          label: "app.bsky.notification.getUnreadCount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-notification-list-activity-subscriptions",
          label: "app.bsky.notification.listActivitySubscriptions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-notification-list-notifications",
          label: "app.bsky.notification.listNotifications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-notification-put-activity-subscription",
          label: "app.bsky.notification.putActivitySubscription",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-notification-put-preferences",
          label: "app.bsky.notification.putPreferences",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-notification-put-preferences-v-2",
          label: "app.bsky.notification.putPreferencesV2",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-notification-register-push",
          label: "app.bsky.notification.registerPush",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-notification-unregister-push",
          label: "app.bsky.notification.unregisterPush",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/app-bsky-notification-update-seen",
          label: "app.bsky.notification.updateSeen",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "app.bsky.video",
      items: [
        {
          type: "doc",
          id: "api/app-bsky-video-get-job-status",
          label: "app.bsky.video.getJobStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-video-get-upload-limits",
          label: "app.bsky.video.getUploadLimits",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/app-bsky-video-upload-video",
          label: "app.bsky.video.uploadVideo",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "chat.bsky.actor",
      items: [
        {
          type: "doc",
          id: "api/chat-bsky-actor-delete-account",
          label: "chat.bsky.actor.deleteAccount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/chat-bsky-actor-export-account-data",
          label: "chat.bsky.actor.exportAccountData",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "chat.bsky.convo",
      items: [
        {
          type: "doc",
          id: "api/chat-bsky-convo-accept-convo",
          label: "chat.bsky.convo.acceptConvo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-add-reaction",
          label: "chat.bsky.convo.addReaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-delete-message-for-self",
          label: "chat.bsky.convo.deleteMessageForSelf",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-get-convo",
          label: "chat.bsky.convo.getConvo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-get-convo-availability",
          label: "chat.bsky.convo.getConvoAvailability",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-get-convo-for-members",
          label: "chat.bsky.convo.getConvoForMembers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-get-log",
          label: "chat.bsky.convo.getLog",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-get-messages",
          label: "chat.bsky.convo.getMessages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-leave-convo",
          label: "chat.bsky.convo.leaveConvo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-list-convos",
          label: "chat.bsky.convo.listConvos",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-mute-convo",
          label: "chat.bsky.convo.muteConvo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-remove-reaction",
          label: "chat.bsky.convo.removeReaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-send-message",
          label: "chat.bsky.convo.sendMessage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-send-message-batch",
          label: "chat.bsky.convo.sendMessageBatch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-unmute-convo",
          label: "chat.bsky.convo.unmuteConvo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-update-all-read",
          label: "chat.bsky.convo.updateAllRead",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/chat-bsky-convo-update-read",
          label: "chat.bsky.convo.updateRead",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "chat.bsky.moderation",
      items: [
        {
          type: "doc",
          id: "api/chat-bsky-moderation-get-actor-metadata",
          label: "chat.bsky.moderation.getActorMetadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/chat-bsky-moderation-get-message-context",
          label: "chat.bsky.moderation.getMessageContext",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/chat-bsky-moderation-update-actor-access",
          label: "chat.bsky.moderation.updateActorAccess",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "com.atproto.admin",
      items: [
        {
          type: "doc",
          id: "api/com-atproto-admin-delete-account",
          label: "com.atproto.admin.deleteAccount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-disable-account-invites",
          label: "com.atproto.admin.disableAccountInvites",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-disable-invite-codes",
          label: "com.atproto.admin.disableInviteCodes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-enable-account-invites",
          label: "com.atproto.admin.enableAccountInvites",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-get-account-info",
          label: "com.atproto.admin.getAccountInfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-get-account-infos",
          label: "com.atproto.admin.getAccountInfos",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-get-invite-codes",
          label: "com.atproto.admin.getInviteCodes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-get-subject-status",
          label: "com.atproto.admin.getSubjectStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-search-accounts",
          label: "com.atproto.admin.searchAccounts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-send-email",
          label: "com.atproto.admin.sendEmail",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-update-account-email",
          label: "com.atproto.admin.updateAccountEmail",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-update-account-handle",
          label: "com.atproto.admin.updateAccountHandle",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-update-account-password",
          label: "com.atproto.admin.updateAccountPassword",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-update-account-signing-key",
          label: "com.atproto.admin.updateAccountSigningKey",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-admin-update-subject-status",
          label: "com.atproto.admin.updateSubjectStatus",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "com.atproto.identity",
      items: [
        {
          type: "doc",
          id: "api/com-atproto-identity-get-recommended-did-credentials",
          label: "com.atproto.identity.getRecommendedDidCredentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-identity-refresh-identity",
          label: "com.atproto.identity.refreshIdentity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-identity-request-plc-operation-signature",
          label: "com.atproto.identity.requestPlcOperationSignature",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-identity-resolve-did",
          label: "com.atproto.identity.resolveDid",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-identity-resolve-handle",
          label: "com.atproto.identity.resolveHandle",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-identity-resolve-identity",
          label: "com.atproto.identity.resolveIdentity",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-identity-sign-plc-operation",
          label: "com.atproto.identity.signPlcOperation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-identity-submit-plc-operation",
          label: "com.atproto.identity.submitPlcOperation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-identity-update-handle",
          label: "com.atproto.identity.updateHandle",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "com.atproto.label",
      items: [
        {
          type: "doc",
          id: "api/com-atproto-label-query-labels",
          label: "com.atproto.label.queryLabels",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "com.atproto.lexicon",
      items: [
        {
          type: "doc",
          id: "api/com-atproto-lexicon-resolve-lexicon",
          label: "com.atproto.lexicon.resolveLexicon",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "com.atproto.moderation",
      items: [
        {
          type: "doc",
          id: "api/com-atproto-moderation-create-report",
          label: "com.atproto.moderation.createReport",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "com.atproto.repo",
      items: [
        {
          type: "doc",
          id: "api/com-atproto-repo-apply-writes",
          label: "com.atproto.repo.applyWrites",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-repo-create-record",
          label: "com.atproto.repo.createRecord",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-repo-delete-record",
          label: "com.atproto.repo.deleteRecord",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-repo-describe-repo",
          label: "com.atproto.repo.describeRepo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-repo-get-record",
          label: "com.atproto.repo.getRecord",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-repo-import-repo",
          label: "com.atproto.repo.importRepo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-repo-list-missing-blobs",
          label: "com.atproto.repo.listMissingBlobs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-repo-list-records",
          label: "com.atproto.repo.listRecords",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-repo-put-record",
          label: "com.atproto.repo.putRecord",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-repo-upload-blob",
          label: "com.atproto.repo.uploadBlob",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "com.atproto.server",
      items: [
        {
          type: "doc",
          id: "api/com-atproto-server-activate-account",
          label: "com.atproto.server.activateAccount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-check-account-status",
          label: "com.atproto.server.checkAccountStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-confirm-email",
          label: "com.atproto.server.confirmEmail",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-create-account",
          label: "com.atproto.server.createAccount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-create-app-password",
          label: "com.atproto.server.createAppPassword",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-create-invite-code",
          label: "com.atproto.server.createInviteCode",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-create-invite-codes",
          label: "com.atproto.server.createInviteCodes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-create-session",
          label: "com.atproto.server.createSession",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-deactivate-account",
          label: "com.atproto.server.deactivateAccount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-delete-account",
          label: "com.atproto.server.deleteAccount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-delete-session",
          label: "com.atproto.server.deleteSession",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-describe-server",
          label: "com.atproto.server.describeServer",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-get-account-invite-codes",
          label: "com.atproto.server.getAccountInviteCodes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-get-service-auth",
          label: "com.atproto.server.getServiceAuth",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-get-session",
          label: "com.atproto.server.getSession",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-list-app-passwords",
          label: "com.atproto.server.listAppPasswords",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-refresh-session",
          label: "com.atproto.server.refreshSession",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-request-account-delete",
          label: "com.atproto.server.requestAccountDelete",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-request-email-confirmation",
          label: "com.atproto.server.requestEmailConfirmation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-request-email-update",
          label: "com.atproto.server.requestEmailUpdate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-request-password-reset",
          label: "com.atproto.server.requestPasswordReset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-reserve-signing-key",
          label: "com.atproto.server.reserveSigningKey",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-reset-password",
          label: "com.atproto.server.resetPassword",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-revoke-app-password",
          label: "com.atproto.server.revokeAppPassword",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-server-update-email",
          label: "com.atproto.server.updateEmail",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "com.atproto.sync",
      items: [
        {
          type: "doc",
          id: "api/com-atproto-sync-get-blob",
          label: "com.atproto.sync.getBlob",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-get-blocks",
          label: "com.atproto.sync.getBlocks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-get-host-status",
          label: "com.atproto.sync.getHostStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-get-latest-commit",
          label: "com.atproto.sync.getLatestCommit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-get-record",
          label: "com.atproto.sync.getRecord",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-get-repo",
          label: "com.atproto.sync.getRepo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-get-repo-status",
          label: "com.atproto.sync.getRepoStatus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-list-blobs",
          label: "com.atproto.sync.listBlobs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-list-hosts",
          label: "com.atproto.sync.listHosts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-list-repos",
          label: "com.atproto.sync.listRepos",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-list-repos-by-collection",
          label: "com.atproto.sync.listReposByCollection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-notify-of-update",
          label: "com.atproto.sync.notifyOfUpdate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/com-atproto-sync-request-crawl",
          label: "com.atproto.sync.requestCrawl",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "tools.ozone.communication",
      items: [
        {
          type: "doc",
          id: "api/tools-ozone-communication-create-template",
          label: "tools.ozone.communication.createTemplate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-communication-delete-template",
          label: "tools.ozone.communication.deleteTemplate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-communication-list-templates",
          label: "tools.ozone.communication.listTemplates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-communication-update-template",
          label: "tools.ozone.communication.updateTemplate",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "tools.ozone.hosting",
      items: [
        {
          type: "doc",
          id: "api/tools-ozone-hosting-get-account-history",
          label: "tools.ozone.hosting.getAccountHistory",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "tools.ozone.moderation",
      items: [
        {
          type: "doc",
          id: "api/tools-ozone-moderation-cancel-scheduled-actions",
          label: "tools.ozone.moderation.cancelScheduledActions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-emit-event",
          label: "tools.ozone.moderation.emitEvent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-get-account-timeline",
          label: "tools.ozone.moderation.getAccountTimeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-get-event",
          label: "tools.ozone.moderation.getEvent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-get-record",
          label: "tools.ozone.moderation.getRecord",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-get-records",
          label: "tools.ozone.moderation.getRecords",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-get-repo",
          label: "tools.ozone.moderation.getRepo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-get-reporter-stats",
          label: "tools.ozone.moderation.getReporterStats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-get-repos",
          label: "tools.ozone.moderation.getRepos",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-get-subjects",
          label: "tools.ozone.moderation.getSubjects",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-list-scheduled-actions",
          label: "tools.ozone.moderation.listScheduledActions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-query-events",
          label: "tools.ozone.moderation.queryEvents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-query-statuses",
          label: "tools.ozone.moderation.queryStatuses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-schedule-action",
          label: "tools.ozone.moderation.scheduleAction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-moderation-search-repos",
          label: "tools.ozone.moderation.searchRepos",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "tools.ozone.safelink",
      items: [
        {
          type: "doc",
          id: "api/tools-ozone-safelink-add-rule",
          label: "tools.ozone.safelink.addRule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-safelink-query-events",
          label: "tools.ozone.safelink.queryEvents",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-safelink-query-rules",
          label: "tools.ozone.safelink.queryRules",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-safelink-remove-rule",
          label: "tools.ozone.safelink.removeRule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-safelink-update-rule",
          label: "tools.ozone.safelink.updateRule",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "tools.ozone.server",
      items: [
        {
          type: "doc",
          id: "api/tools-ozone-server-get-config",
          label: "tools.ozone.server.getConfig",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "tools.ozone.set",
      items: [
        {
          type: "doc",
          id: "api/tools-ozone-set-add-values",
          label: "tools.ozone.set.addValues",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-set-delete-set",
          label: "tools.ozone.set.deleteSet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-set-delete-values",
          label: "tools.ozone.set.deleteValues",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-set-get-values",
          label: "tools.ozone.set.getValues",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-set-query-sets",
          label: "tools.ozone.set.querySets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-set-upsert-set",
          label: "tools.ozone.set.upsertSet",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "tools.ozone.setting",
      items: [
        {
          type: "doc",
          id: "api/tools-ozone-setting-list-options",
          label: "tools.ozone.setting.listOptions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-setting-remove-options",
          label: "tools.ozone.setting.removeOptions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-setting-upsert-option",
          label: "tools.ozone.setting.upsertOption",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "tools.ozone.signature",
      items: [
        {
          type: "doc",
          id: "api/tools-ozone-signature-find-correlation",
          label: "tools.ozone.signature.findCorrelation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-signature-find-related-accounts",
          label: "tools.ozone.signature.findRelatedAccounts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-signature-search-accounts",
          label: "tools.ozone.signature.searchAccounts",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "tools.ozone.team",
      items: [
        {
          type: "doc",
          id: "api/tools-ozone-team-add-member",
          label: "tools.ozone.team.addMember",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-team-delete-member",
          label: "tools.ozone.team.deleteMember",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-team-list-members",
          label: "tools.ozone.team.listMembers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-team-update-member",
          label: "tools.ozone.team.updateMember",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "tools.ozone.verification",
      items: [
        {
          type: "doc",
          id: "api/tools-ozone-verification-grant-verifications",
          label: "tools.ozone.verification.grantVerifications",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tools-ozone-verification-list-verifications",
          label: "tools.ozone.verification.listVerifications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tools-ozone-verification-revoke-verifications",
          label: "tools.ozone.verification.revokeVerifications",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
